gui:
  statusPanelView: allBranchesLog
  skipDiscardChangeWarning: true
  theme:
    selectedLineBgColor:
      - reverse
  nerdFontsVersion: "3"
git:
  paging:
    colorArg: always
    pager: delta --light --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  log:
    showWholeGraph: true
